/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp measurement.xml -a measurementAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MEASUREMENTADAPTOR_H_1460550007
#define MEASUREMENTADAPTOR_H_1460550007

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface local.Measurement
 */
class MeasurementAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "xml.Measurement")

public:
    MeasurementAdaptor(QObject *parent);
    virtual ~MeasurementAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString getDateMeasurement();
    QString getTimeMeasurement();
Q_SIGNALS: // SIGNALS
};

#endif
