/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp measurement.xml -a measurementAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "measurementAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeasurementAdaptor
 */

MeasurementAdaptor::MeasurementAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeasurementAdaptor::~MeasurementAdaptor()
{
    // destructor
}

QString MeasurementAdaptor::getDateMeasurement()
{
    // handle method call local.Measurement.getDateMeasurement
    QString out0;
    QMetaObject::invokeMethod(parent(), "getDateMeasurement", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString MeasurementAdaptor::getTimeMeasurement()
{
    // handle method call local.Measurement.getTimeMeasurement
    QString out0;
    QMetaObject::invokeMethod(parent(), "getTimeMeasurement", Q_RETURN_ARG(QString, out0));
    return out0;
}

