/*------------------------------------------------------------------------------------------------

# Copyright (c) 2016 Núcleo de Tecnologias Estratégicas em Saúde (NUTES)/Signove Tecnologia S/A .
# Licensed under the MIT license;
# You may obtain a copy of the License at:
# http://opensource.org/licenses/mit-license.php or see LICENSE file

------------------------------------------------------------------------------------------------

 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp bluetoothdevice.xml -p bluetoothDeviceInterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "bluetoothDeviceInterface.h"

/*
 * Implementation of interface class ConectividadeBluetoothDeviceInterface
 */

ConectividadeBluetoothDeviceInterface::ConectividadeBluetoothDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ConectividadeBluetoothDeviceInterface::~ConectividadeBluetoothDeviceInterface()
{
}

