/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp agent.xml -a agentAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "agentAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentAdaptor
 */

AgentAdaptor::AgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentAdaptor::~AgentAdaptor()
{
    // destructor
}

void AgentAdaptor::Connected(const QString &device, const QString &address)
{
    // handle method call local.Agent.Connected
    QMetaObject::invokeMethod(parent(), "Connected", Q_ARG(QString, device), Q_ARG(QString, address));
}

void AgentAdaptor::Associated(const QString &device, const QString &xmlData)
{
    QMetaObject::invokeMethod(parent(), "Associated", Q_ARG(QString, device), Q_ARG(QString, xmlData));
}

void AgentAdaptor::MeasurementData(const QString &device, const QString &xmlData)
{
    QMetaObject::invokeMethod(parent(), "MeasurementData", Q_ARG(QString, device), Q_ARG(QString, xmlData));
}

void AgentAdaptor::DeviceAttributes(QString device, QString xmlData)
{
    QMetaObject::invokeMethod(parent(), "DeviceAttributes", Q_ARG(QString, device), Q_ARG(QString, xmlData));
}

void AgentAdaptor::Disassociated(const QString &device)
{
    QMetaObject::invokeMethod(parent(), "Disassociated", Q_ARG(QString, device));
}

void AgentAdaptor::Disconnected(const QString &device)
{
    QMetaObject::invokeMethod(parent(), "Disconnected", Q_ARG(QString, device));
}

